# docker-compose.yml
version: '2.1'

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - APP_URL=${APP_URL}
      - DB_HOST=bookstack_db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_KEY=${APP_KEY}
      - REGISTRATION_ENABLED=true

    volumes:
      - app_config:/config
    ports:
      - 9000:80
    restart: unless-stopped
    networks:
      - bookstack_network
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/config
    networks:
      - bookstack_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=bookstack_db
      - PMA_PORT=${DB_PORT}
    ports:
      - "8080:80"
    depends_on:
      - bookstack_db
    networks:
      - bookstack_network

volumes:
  app_config:
  db_data:

networks:
  bookstack_network:
    driver: bridge
